-- Datos sacados de la carpeta de 'diagram' del proyecto

CREATE TABLE "bg04_category" (
    "id_category" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "tx_name" VARCHAR (225) NOT NULL
);

CREATE TABLE "bg01_blog" (
    "id_blog" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "title" VARCHAR(255) NOT NULL,
    "tx_title" VARCHAR(225) NOT NULL,
    "md_content" TEXT NOT NULL,
    "tm_createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "tm_updatedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "fk_id_category" INTEGER NOT NULL,
    FOREIGN KEY ("fk_id_category") REFERENCES "bg04_category" ("id_category") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE "bg02_tag" (
    "id_tag" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "tx_nombre" VARCHAR(225) NOT NULL
);

CREATE TABLE "bg03_blog_tag" (
    "id_blog_tag" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "fk_id_blog" INTEGER NOT NULL,
    "fk_id_tag" INTEGER NOT NULL,
    FOREIGN KEY ("fk_id_blog") REFERENCES "bg01_blog" ("id_blog") ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY ("fk_id_tag") REFERENCES "bg02_tag" ("id_tag") ON DELETE CASCADE ON UPDATE CASCADE
);



